version: "3"

tasks:
  generate_client_code:
    desc: "Generates client code from .proto files"
    cmds:
      - task clear_generated
      # - |
      #   protoc  --proto_path=../protos ../protos/*.proto \
      #   --plugin=protoc-gen-grpc-web=./node_modules/.bin/protoc-gen-grpc-web \
      #   --js_out=import_style=commonjs,binary:src/generated \
      #   --grpc-web_out=import_style=typescript,mode=grpcweb:src/generated \
      - |
        npx protoc \
        --ts_out src/generated/ \
        --ts_opt long_type_string \
        --proto_path ../protos \
        ../protos/*.proto
    
      # - |
      #   protoc  --proto_path=../protos ../protos/*.proto \
      #   --plugin=protoc-gen-grpc-web=./node_modules/.bin/protoc-gen-grpc-web \
      #   --grpc-web_out=import_style=typescript,mode=grpcwebtext:src/generated \
      
      # - |
      #   protoc  --proto_path=../protos ../protos/*.proto \
      #   --plugin=protoc-gen-grpc-web=./node_modules/.bin/protoc-gen-grpc-web \
      #   --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
      #   --ts_out src/generated \
      #   --grpc-web_out=import_style=typescript,mode=grpcwebtext:src/generated \
      
      # - |
      #   protoc  --proto_path=../protos ../protos/*.proto \
      #   --plugin=protoc-gen-grpc-web=./node_modules/.bin/protoc-gen-grpc-web \
      #   --js_out=import_style=es6:src/generated \
      #   --grpc-web_out=import_style=typescript,mode=grpcwebtext:src/generated \

  clear_generated:
    desc: "clears generated folder"
    cmds:
      - rm -rf src/generated/*
